//
//  BullsAndCowsGame.swift
//  ICS3UCulminating
//
//  Created by Gemini CLI on 2026-06-02.
//

import Foundation

// MARK: - Model

/// This structure manages the core logic of the Bulls and Cows game.
/// It is responsible for generating the secret code and evaluating guesses.
struct BullsAndCowsGame {
    
    // MARK: - Stored properties
    
    /// The secret 4-digit code generated by the game.
    private(set) var secretCode: String = ""
    
    /// The length of the secret code (standard is 4).
    let codeLength: Int = 4
    
    // MARK: - Initializer
    
    /// Initializes a new game and generates a secret code.
    init() {
        self.generateSecretCode()
    }
    
    // MARK: - Functions
    
    /// Generates a secret code with unique digits.
    private mutating func generateSecretCode() {
        // Our pool of choices (1-9)
        var digits: [Int] = [1, 2, 3, 4, 5, 6, 7, 8, 9]
        var result = ""
        
        // We repeat this process until we have exactly 4 digits
        for _ in 1...4 {
            // 1. Randomly pick an index from the digits left in the pool
            let randomIndex = Int.random(in: 0..<digits.count)
            
            // 2. Get the number at that index and add it to our result string
            let chosenNumber = digits[randomIndex]
            result += String(chosenNumber)
            
            // 3. Remove that specific number from the pool so it cannot be picked again
            digits.remove(at: randomIndex)
        }
        
        self.secretCode = result
    }
    
    /// Evaluates a guess and returns a GuessResult containing Bulls and Cows counts.
    /// - Parameter guess: The 4-digit string guessed by the player.
    /// - Returns: A GuessResult object.
    func checkGuess(_ guess: String) -> GuessResult {
        var bullsCount = 0
        var cowsCount = 0
        
        // Convert strings to arrays of characters for easy comparison
        let secretArray = Array(secretCode)
        let guessArray = Array(guess)
        
        // Step-by-step evaluation using loops (as per project style)
        for i in 0..<codeLength {
            if guessArray[i] == secretArray[i] {
                // Correct digit in correct position
                bullsCount += 1
            } else {
                // Check if the digit exists elsewhere in the secret code
                for j in 0..<codeLength {
                    if guessArray[i] == secretArray[j] {
                        cowsCount += 1
                        break // Found the match, move to next guess digit
                    }
                }
            }
        }
        
        return GuessResult(guess: guess, bulls: bullsCount, cows: cowsCount)
    }
}
